spring:
  application:
    name: boot-blog
  # ?? ?? ??
  profiles:
    active: dev
    # ??? ? Docker? ???? prod? ????

#  # ??? ? ??
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      maximum-pool-size: 10 # ?? ??? ?
#      minimum-idle: 5 # ?? ?? ??? ?

#  # MyBatis ??
#  mybatis:
#    #    mapper-locations: classpath:mapper/*.xml # ?? XML ?? ?? ??
#    type-aliases-package: org.example.bootsecurityplus.model.domain # ??? ?? ??? ??
#    configuration:
#      map-underscore-to-camel-case: true # ????? ???? ?? ??? ????? ?? ??

  # ????
  security :
    user :
      name: hello
      password : world

  # JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true # ?? ???? SQL ?? ??
    properties.hibernate.format_sql: true